tasks:
  - init: |
      ./lila-docker build
      git clone --depth 1 --origin upstream https://github.com/lichess-org/lila repos/lila
      git clone --depth 1 --origin upstream https://github.com/lichess-org/lila-ws repos/lila-ws
      git clone --depth 1 --origin upstream https://github.com/lichess-org/lila-db-seed repos/lila-db-seed
      git clone --depth 1 --origin upstream https://github.com/lichess-org/lifat repos/lifat
      git -C repos/lila submodule update --init
      touch .env
      docker compose run --rm -it lila_docker_rs bash -c "cargo build --manifest-path /mnt/Cargo.toml"
  - command: |
      ./lila-docker start
      ./lila-docker gitpod-welcome

ports:
  - port: 8080
    name: lichess
    description: Lichess dev site
    onOpen: open-preview
  - port: 8025
    name: mailpit
    description: Email inbox
    onOpen: ignore
  - port: 8081
    name: mongo-express
    description: "Database explorer (u: admin / p: pass)"
    onOpen: ignore
  - port: 8089
    name: API docs
    onOpen: ignore
  - port: 8090
    name: chessground
    onOpen: ignore
  - port: 8091
    name: pgn-viewer
    onOpen: ignore
  - port: 9666
    name: lila-engine
    description: External engine
    onOpen: ignore
  - port: 6175
    name: lila-gif
    onOpen: ignore
  - port: 3001
    name: picfit
    onOpen: ignore
  - port: 5601
    name: kibana
    description: Elasticsearch manager
    onOpen: ignore

vscode:
  extensions:
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - scala-lang.scala
